"""State schema for multi-agent workflows."""

from operator import add
from typing import Annotated, Any, Dict, List, Optional, TypedDict


def merge_lists(existing: List[Any], incoming: List[Any]) -> List[Any]:
    """Append new items instead of overwriting list state."""
    return [*existing, *incoming]


class TrendItem(TypedDict, total=False):
    """Single trend candidate discovered by research tools or agents."""

    name: str
    source: str
    region: str
    score: float
    summary: str
    metadata: Dict[str, Any]


class PostDraft(TypedDict, total=False):
    """Candidate social post generated by the workflow."""

    content: str
    platform: str
    tone: str
    hashtags: List[str]
    rationale: str
    metadata: Dict[str, Any]


class ApprovedPost(TypedDict, total=False):
    """Final approved post ready for publishing."""

    content: str
    platform: str
    hashtags: List[str]
    approved_by: str
    approved_at: str
    metadata: Dict[str, Any]


class EngagementMetrics(TypedDict, total=False):
    """JSON-serializable performance metrics after publishing."""

    platform: str
    impressions: int
    likes: int
    comments: int
    shares: int
    clicks: int
    engagement_rate: float
    captured_at: str
    metadata: Dict[str, Any]


class AgentState(TypedDict, total=False):
    """Shared notebook for all agents in the multi-agent graph."""

    schema_version: str

    # Input
    input: str
    region: str

    # Social-media workflow state
    trends: Annotated[List[TrendItem], merge_lists]
    selected_trend: Optional[TrendItem]
    post_drafts: Annotated[List[PostDraft], merge_lists]
    approved_post: Optional[ApprovedPost]
    engagement_metrics: Annotated[List[EngagementMetrics], merge_lists]

    # Coordinator outputs
    plan: Dict[str, Any]
    next_agent: str
    coordinator_status: str

    # Processor outputs
    processed_output: Dict[str, Any]
    processor_status: str
    processor_confidence: float

    # Validator outputs
    validation_result: Dict[str, Any]
    is_valid: bool
    validator_status: str
    validation_score: float
    issues: Annotated[List[str], add]

    # Final output
    final_output: Dict[str, Any]

    # Workflow control
    retry_count: int
    max_retries: int
    current_agent: str
    workflow_status: str

    # Observability
    execution_history: Annotated[List[str], add]


class ToolExecutionState(TypedDict, total=False):
    """State for tool execution."""

    tool_name: str
    tool_input: Dict[str, Any]
    tool_output: Any
    tool_status: str
    error: Optional[str]
