"""State schema for multi-agent workflows."""

from typing import Annotated, Dict, List, Literal, Optional, TypeVar, TypedDict, Union

SCHEMA_VERSION = "1.0"
JSONPrimitive = Union[str, int, float, bool, None]
JSONList = List[JSONPrimitive]
JSONValue = Union[JSONPrimitive, JSONList]
Metadata = Dict[str, JSONValue]
T = TypeVar("T")


def merge_lists(existing: List[T], incoming: List[T]) -> List[T]:
    """Append new items instead of overwriting list state."""
    return [*existing, *incoming]


class PlanStep(TypedDict, total=False):
    """Single step in the coordinator plan."""

    name: str
    status: str
    description: str


class AgentPlan(TypedDict, total=False):
    """Coordinator output describing how the workflow should proceed."""

    task: str
    complexity: float
    steps: List[PlanStep]
    priority: str
    requires_tools: List[str]
    next_agent: str
    intent: str


class ProcessedOutput(TypedDict, total=False):
    """Normalized processor output shared with downstream agents."""

    original_input: str
    transformed_input: str
    plan_executed: str
    result: str
    intent: str
    error: str
    error_details: str
    trends_data: Metadata
    metadata: Metadata


class ValidationResult(TypedDict, total=False):
    """Validator output describing quality and retry decisions."""

    is_valid: bool
    quality_score: float
    checks_passed: List[str]
    issues: List[str]
    needs_retry: bool


class FinalOutput(TypedDict, total=False):
    """Final workflow payload returned at the end of execution."""

    result: str
    validation: ValidationResult
    status: str
    retry_count: int


class TrendItem(TypedDict, total=False):
    """Single trend candidate discovered by research tools or agents."""

    name: str
    source: str
    region: str
    score: float
    summary: str
    metadata: Metadata


class PostDraft(TypedDict, total=False):
    """Candidate social post generated by the workflow."""

    content: str
    platform: str
    tone: str
    hashtags: List[str]
    rationale: str
    metadata: Metadata


class ApprovedPost(TypedDict, total=False):
    """Final approved post ready for publishing."""

    content: str
    platform: str
    hashtags: List[str]
    approved_by: str
    approved_at: str
    metadata: Metadata


class EngagementMetrics(TypedDict, total=False):
    """JSON-serializable performance metrics after publishing."""

    platform: str
    impressions: int
    likes: int
    comments: int
    shares: int
    clicks: int
    engagement_rate: float
    captured_at: str
    metadata: Metadata


class AgentState(TypedDict, total=False):
    """Shared notebook for all agents in the multi-agent graph."""

    schema_version: Literal["1.0"]

    # Input
    input: str
    region: str

    # Social-media workflow state
    trends: Annotated[List[TrendItem], merge_lists]
    selected_trend: Optional[TrendItem]
    post_drafts: Annotated[List[PostDraft], merge_lists]
    approved_post: Optional[ApprovedPost]
    engagement_metrics: Annotated[List[EngagementMetrics], merge_lists]

    # Coordinator outputs
    plan: AgentPlan
    next_agent: str
    coordinator_status: str

    # Processor outputs
    processed_output: ProcessedOutput
    processor_status: str
    processor_confidence: float

    # Validator outputs
    validation_result: ValidationResult
    is_valid: bool
    validator_status: str
    validation_score: float
    issues: List[str]

    # Final output
    final_output: FinalOutput

    # Workflow control
    retry_count: int
    max_retries: int
    current_agent: str
    workflow_status: str

    # Observability
    execution_history: List[str]
